# Configuration for Replit deployment
run = "npm run dev"
language = "nodejs"
hidden = [".vercel", "build", ".env", ".gitignore", "vite-env.d.ts", ".replit", "node_modules"]

[env]
NODE_ENV = "production"
PORT = "3000"
# Add other environment variables as needed

[packager]
language = "nodejs"

[languages.typescript]
pattern = "**/{*.ts,*.tsx}"
syntax = "typescript"

[languages.typescript.languageServer]
start = [ "typescript-language-server", "--stdio" ]

[deployment]
type = "static"
build = ["npm", "run", "build"]
deploymentTarget = "node"
publicDir = "dist"
startCommand = "NODE_ENV=production node server/index.js"

[hosting]
route = "/"

# Ensure that API requests are properly handled
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200